owncloud/user_ldap

lib/Access.php
lib/Configuration.php
lib/Connection.php
lib/Group_LDAP.php
lib/User/User.php
lib/User_LDAP.php
lib/Wizard.php
tests/AccessTest.php
tests/ConnectionTest.php
tests/Group_LDAPTest.php
tests/Jobs/CleanUpTest.php
tests/Mapping/AbstractMappingTest.php
tests/User/ManagerTest.php
tests/User/UserTest.php
tests/User_LDAPTest.php
tests/WizardTest.php

Ported and squashed https://github.com/owncloud/core/pull/25689

Harden empty

---

lib/Access.php

Remove commented function

---

lib/Command/UpdateGroup.php

Fix https://github.com/owncloud/user_ldap/issues/20

Skip over missing groups

---

ajax/wizard.php

No linked issue that I'm aware.
@owncloud/qa we'll need to test this.
@PVince81 Not sure if we'll need to backport or not.

Add prefix to the connection

---

lib/Command/ShowConfig.php
lib/Command/ShowRemnants.php

Fixes https://github.com/owncloud/user_ldap/issues/16
Please review @jvillafanez @DeepDiver1975

Fix symfony console table

---

lib/Connection.php

Fixes: https://github.com/owncloud/enterprise/issues/1756

Base tree for Gropus is empty using BaseDN set to debug mode

---

lib/Group_Proxy.php
tests/Integration/AbstractIntegrationTest.php
tests/Integration/Lib/User/IntegrationTestUserAvatar.php
tests/Integration/Lib/User/IntegrationTestUserDisplayName.php
tests/Integration/setup-scripts/createExplicitGroups.php
tests/Integration/setup-scripts/createExplicitGroupsDifferentOU.php
tests/Integration/setup-scripts/createExplicitUsers.php

@jvillafanez @DeepDiver1975 I'm trying to get the user logged in before getting the avatar or displayname. Not working so far. Do you know what I am doing wrong?

Trying to login the user before doing anything with it

---

appinfo/app.php

Use the proxy classes instead of the non-proxy ones.
Tests might need adjustment / improvement to use the proxy classes. Other than that I haven't detect any issue.

Use proxy classes

---

.bowerrc
Makefile
bower.json
composer.json
composer.lock
package.json

Fix https://github.com/owncloud/user_ldap/issues/83
Note that there are updates for the dev libraries for phpunit. This shouldn't affect the app, just the tests, not sure how they will be affected though. We can use the old ones because all those dependencies are for phpunit.
**Please, verify all the data is correct**
@PVince81

add script for marketplace releasing

---

appinfo/info.xml

Added more information for the marketplace

added category and screenshot, removed old job

---

lib/Access.php
lib/Connection.php

fixes https://github.com/owncloud/user_ldap/issues/33

autodetect 'ipauniqueid' in Connection as well

---

lib/Access.php

Fix https://github.com/owncloud/user_ldap/issues/74 as suggested in https://github.com/owncloud/user_ldap/issues/74#issuecomment-298956930
@tomneedham please check this is what you tested.

Ignore illegal char when we try to convert the username

---

appinfo/info.xml

Increase minimum version to 10.0.1

---

lib/User_LDAP.php
lib/User_Proxy.php

fix getting search terms in case the different ldap servers use different base dns.
no release blocker. can be released via market. cc @DeepDiver1975 for releasing asap?

allow proxy to check next server

---

lib/User/User.php
tests/User/UserTest.php

Port of https://github.com/owncloud/core/pull/28404
Tested in 9.1.x but not in 10.0 yet

Keep the current quota if no suitable quota is found

---

.travis.yml

fix travis problems with php 7.0

Remove fix for ldap installation

---

lib/Connection.php

Manual port of https://github.com/owncloud/core/pull/27598
Original issue: https://github.com/owncloud/core/issues/27575
Not tested yet with 10.0 (the original patch was partially tested with 9.1 -> https://github.com/owncloud/core/pull/27598#issuecomment-292905373)

Fix working with LDAP replica server

---

lib/Access.php
lib/User/UserEntry.php
tests/User/UserEntryTest.php

@patrickjahns https://github.com/owncloud/user_ldap/pull/143 was against wrong branch

do not trim uuid

---

lib/User_LDAP.php
lib/User_Proxy.php

release port of https://github.com/owncloud/user_ldap/pull/151

fake set displayname support

---

lib/User/Manager.php

fixes syncing when a custom uuid attribute is configured

use custom uuid attribute if configured

---

appinfo/info.xml

Added some marketing introduction and some formal stuff quickly. This is kind of WIP
- Need a new screenshot/title image @hurradieweltgehtunter 
- More input very welcome @tobiherr @tomneedham @butonic

WIP - add summary, docs; change name, description

---

.drone.yml
tests/Integration/AbstractIntegrationTest.php
tests/Integration/setup-scripts/config.php

move the integration tests to drone, including a small fix to the tests themself

run integration tests in drone

---

.travis.yml
appinfo/info.xml

and adjust Travis test matrix.

Bump min version to 10.1 for core master changes

---

lib/Access.php

These tiny things keep annoying me ... get the issues  down a little. one class after another.

Stop being distracted by annoyances in access.php

---

.drone.yml
.travis.yml
composer.json
composer.lock
tests/User_LDAPTest.php

leaving tests on travis running for now in parallel

add lint and phpunit tests to drone

---

.drone.yml
tests/acceptance/config/behat.yml
tests/acceptance/features/avatar.feature
tests/acceptance/features/bootstrap/bootstrap.php
tests/acceptance/features/changingDisplayName.feature
tests/acceptance/features/changingPassword.feature
tests/acceptance/features/loginUsingEmailAddress.feature

keep up with changes in core https://github.com/owncloud/core/pull/30722

sync with changes in core (move of UI tests)

---

tests/acceptance/features/avatar.feature
tests/acceptance/features/changingDisplayName.feature
tests/acceptance/features/changingPassword.feature
tests/acceptance/features/loginUsingEmailAddress.feature

Make minimal changes necessary due to changes to gherkin test step text in core.

Refactor UI test steps to core format

---

tests/acceptance/config/behat.yml
tests/acceptance/features/bootstrap/UserLdapContext.php
tests/acceptance/features/bootstrap/bootstrap.php
tests/acceptance/features/paging.feature

tests that check basic user interaction when the paging is set to a lower number than the amount of users

acceptance tests with a lot of users (to test paging)

---

tests/acceptance/config/behat.yml
tests/acceptance/features/bootstrap/UserLdapGeneralContext.php
tests/acceptance/features/bootstrap/UserLdapUsersContext.php
tests/acceptance/features/groupMembership.feature
tests/acceptance/features/paging.feature

some tests testing various scenarios for group membership

acceptance tests for group membership

---

tests/acceptance/config/behat.yml
tests/acceptance/features/bootstrap/UserLdapGeneralContext.php
tests/acceptance/features/bootstrap/bootstrap.php

and other goodies to make acceptance tests work.

Refactor acceptance tests for core changes

---

.drone.yml

- use the proper codecov plugin 
- report status failures into channel (for nightly runs)
- logging should only be required on failure

[DRONE] cleanup drone yml

---

tests/acceptance/config/behat.yml
tests/acceptance/features/bootstrap/UserLdapGeneralContext.php

to match core changes in https://github.com/owncloud/core/pull/30943

Remove /ocs/ from end of acceptance tests baseUrl

---

CHANGELOG.md
appinfo/info.xml

release 0.11.0

---

.drone.yml
.phan/config.php
Makefile

With https://github.com/owncloud/core/pull/31807 it was a POC for using phan in core for detecting bugs / problems
This PR introduces phan with a lenient configuration to an app and shows how it needs to be configured for testing.
Once this is merged, the next steps include in making the checking stricter and adressing the issues found by phan
Edit: note that i've added quite a few people as reviewers to draw attention and discuss it

add phan as static code anaylser

---

appinfo/install.php
lib/Jobs/UpdateGroups.php

refs https://github.com/owncloud/core/pull/32062

Remove deprecated \OCP\Config calls

---

.drone.yml
tests/acceptance/config/behat.yml
tests/acceptance/config/ldap-users.ldif

run API tests of core in an LDAP environment
~~blocked by https://github.com/owncloud/user_ldap/issues/268~~
lets not get blocked, but skip that test https://github.com/owncloud/core/pull/32349

run core api tests

---

tests/acceptance/features/bootstrap/UserLdapGeneralContext.php
tests/acceptance/features/bootstrap/UserLdapUsersContext.php
tests/acceptance/features/webUIUserLDAP/avatar.feature
tests/acceptance/features/webUIUserLDAP/changingDisplayName.feature
tests/acceptance/features/webUIUserLDAP/changingPassword.feature
tests/acceptance/features/webUIUserLDAP/groupMembership.feature
tests/acceptance/features/webUIUserLDAP/loginUsingEmailAddress.feature
tests/acceptance/features/webUIUserLDAP/paging.feature

like done in core PR https://github.com/owncloud/core/pull/32443

Be consistent in acceptance test steps 'when the administrator'

---

.drone.yml

use mysql 5.7 in CI

---

.drone.yml

add PHP versions for unit tests

Php72 drone

---

tests/acceptance/config/behat.yml
tests/acceptance/config/ldap-users.ldif
tests/acceptance/features/webUIUserLDAP/avatar.feature
tests/acceptance/features/webUIUserLDAP/changingDisplayName.feature
tests/acceptance/features/webUIUserLDAP/groupMembership.feature
tests/acceptance/features/webUIUserLDAP/loginUsingEmailAddress.feature

and while I am here, sort the lists of contexts into alphabetical order to make it easier to compare to core.

Update Behat contexts needed for core acceptance tests

---

tests/acceptance/features/bootstrap/UserLdapGeneralContext.php
tests/acceptance/features/webUIUserLDAP/avatar.feature
tests/acceptance/features/webUIUserLDAP/changingDisplayName.feature
tests/acceptance/features/webUIUserLDAP/changingPassword.feature
tests/acceptance/features/webUIUserLDAP/groupMembership.feature
tests/acceptance/features/webUIUserLDAP/loginUsingEmailAddress.feature
tests/acceptance/features/webUIUserLDAP/paging.feature

1) Indent feature files 2-characters 
2) Remove passwords and update email addresses in tests 
3) Pass empty values to runOcc() as quoted empty string
4) Use the ordinary user create step to create users for group membership tests
(just using the initialize step causes problems with the users not being really remembered by the test code, and so not be cleaned up...)

Test refactor 20181004

---

appinfo/info.xml

Update release branch max-version to 11.0.0.0 for switching to Semver.

update release branch max-version to 11.0.0.0

---

.drone.yml

move tests from travis to drone
Related to #273

Add more tests to drone

---

.drone.yml

no need to start the mysql server for every test

only start mysql server when needed

---

appinfo/info.xml

to master as there are still outstanding PRs for the release ticket

Set max version to 10 for Semver

---

Makefile

Remove phar

---

tests/acceptance/config/behat.yml

that was created in core yesterday

Add new core PublicWebDavContext

---

tests/acceptance/config/behat.yml

that was added by core PR https://github.com/owncloud/core/pull/34029

Add new TrashbinContext from core

---

.drone.yml
tests/acceptance/config/behat.yml
tests/acceptance/features/bootstrap/UserLdapGeneralContext.php
tests/acceptance/features/cliProvisioning/groups.feature
tests/acceptance/features/cliProvisioning/users.feature

Related to issue #292
Add cli tests to run to check that the basic user and group features
work when the user_ldap app is enabled

Add CLI tests for user and groups

---

.drone.yml
Makefile
tests/acceptance/config/behat.yml
tests/acceptance/features/apiUserLDAPConnection/serverConnection.feature
tests/acceptance/features/bootstrap/UserLdapGeneralContext.php

tests to check if authorization works correctly with various settings
needs https://github.com/owncloud/core/pull/34155

various tests to test connections to LDAP server

---

Makefile
phpcs.xml
tests/acceptance/features/bootstrap/UserLdapGeneralContext.php
vendor-bin/php_codesniffer/composer.json

Like was merged in core in https://github.com/owncloud/core/pull/34191
So that we know if we break our own rules for acceptance test code style.

Add php codesniffer

---

.drone.yml
tests/acceptance/config/behat.yml
tests/acceptance/features/apiUserLDAPSharing/sharingLocalUserLdapUser.feature

check if database and LDAP users can interact correctly

 tests sharing between database and LDAP users 

---

tests/acceptance/features/apiUserLDAPConnection/backupServerConnection.feature

test if ownCloud works correctly when the main server is unreachable but the backup server is online

test connection to backup server

---

.drone.yml
Makefile
tests/acceptance/config/behat.yml

Related Issue #354
Add more core acceptance tests for user_ldap.

Run all relevent core tests in user_ldap

---

tests/acceptance/config/behat.yml

some steps need `WebDavPropertiesContext`
after https://github.com/owncloud/core/pull/34229

add missing context

---

tests/acceptance/config/behat.yml
tests/acceptance/features/apiUserLDAPConnection/groupFilter.feature
tests/acceptance/features/bootstrap/UserLdapGeneralContext.php

as requested in https://github.com/owncloud/user_ldap/issues/35
needs https://github.com/owncloud/core/pull/34398 to be merged and QA tarball rebuild

test group filters

---

.drone.yml
tests/acceptance/config/behat.yml

Add apiAuth core acceptance test suite

---

.drone.yml
appinfo/info.xml
composer.json
composer.lock
tests/acceptance/config/behat.yml
tests/acceptance/features/cliProvisioning/groups.feature
tests/acceptance/features/webUIProvisioning/groups.feature
vendor-bin/behat/composer.json

1) core stable10 no longer supports PHP 5.6
https://github.com/owncloud/core/pull/34698
2) core added `WebUIPersonalSharingSettingsContext` and steps it it are now needed for `webUICore` suite. So add that to `behat.yml`

Drop PHP 5.6

---

lib/Connection.php
lib/User/UserEntry.php
tests/unit/ConnectionTest.php
tests/unit/Controller/MappingControllerTest.php
tests/unit/Controller/WizardControllerTest.php

Remove unused use statements

---

tests/unit/AccessTest.php
tests/unit/CommandTest.php
tests/unit/ConnectionTest.php
tests/unit/Controller/ConfigurationControllerTest.php
tests/unit/Controller/MappingControllerTest.php
tests/unit/Controller/WizardControllerTest.php
tests/unit/Group_LDAPTest.php
tests/unit/User/ManagerTest.php
tests/unit/User/UserEntryTest.php
tests/unit/User_LDAPTest.php
tests/unit/WizardTest.php

1) Adjust PHPUnit Framework namespace for PHPUnit6

Adjust PHPUnit Framework namespace for PHPUnit6

---

lib/Helper.php

loginName2UserName is already called for an object, not a class 

---

Makefile
phpunit.xml
tests/unit/AppInfo/ApplicationTest.php
tests/unit/Controller/ConfigurationControllerTest.php

and remove accidentally duplicated `help` target in `Makefile` - see comment https://github.com/owncloud/user_ldap/pull/402#discussion_r271462326 in #402

phpunit enable failOnRisky

---

tests/acceptance/features/apiProvisioningLDAP/users.feature
tests/acceptance/features/webUIProvisioning/users.feature

test quota sync with LDAP

---

.drone.yml
tests/acceptance/config/behat.yml
tests/acceptance/features/apiUserLDAPConnection/backupServerConnection.feature
tests/acceptance/features/apiUserLDAPConnection/serverConnection.feature
tests/acceptance/features/bootstrap/UserLdapGeneralContext.php

run tests on LDAPS

---

.drone.yml
tests/acceptance/config/behat.yml
tests/acceptance/features/apiProvisioningLDAP/groups.feature
tests/acceptance/features/apiProvisioningLDAP/users.feature
tests/acceptance/features/apiUserLDAP/moveUser.feature

following up  #165 some additional tests for user & groups. Make sure they are not duplicated
fixes #417

additional user/groups based tests

---

tests/acceptance/features/webUIUserLDAP/groupMembership.feature

Adjust create user test steps

---

.drone.yml
tests/acceptance/config/behat.yml

added in core by https://github.com/owncloud/core/pull/35725
and https://github.com/owncloud/core/pull/35726

Add new api share core suites

---

lib/LDAP.php

A logging except from https://github.com/owncloud/user_ldap/pull/332
Code is not testable as it depends on a native `ldap_error` function.
Context: https://github.com/owncloud/enterprise/issues/3063

Log bind errors

---

lib/Connection.php
tests/unit/ConnectionTest.php

extracted from https://github.com/owncloud/user_ldap/pull/332 
trying to localize the  part breaking acceptance tests

Simplify connection: Get rid of init method

---

.drone.yml

Add new restrictions to .drone.yml
Execute ci on ` master, release*, next* `branches.

Add branch specific restrictions to .drone.yml

---

CHANGELOG.md
appinfo/info.xml

Add changelog items and bump version to 0.14.0

Add changelog items and bump version

---

tests/unit/Controller/ConfigurationControllerTest.php

Fix testCreateWithCopy PHP unit test

---

.drone.starlark
.drone.yml
tests/acceptance/config/behat.yml
tests/integration/ExceptionOnLostConnection.php
tests/unit/AccessTest.php
tests/unit/CommandTest.php
tests/unit/ConfigurationTest.php
tests/unit/ConnectionTest.php
tests/unit/Controller/ConfigurationControllerTest.php
tests/unit/Controller/MappingControllerTest.php
tests/unit/Controller/WizardControllerTest.php
tests/unit/Group_LDAPTest.php
tests/unit/User/ManagerTest.php
tests/unit/User/UserEntryTest.php
tests/unit/User_LDAPTest.php
tests/unit/WizardTest.php
vendor-bin/behat/composer.json

Similar to https://github.com/owncloud/configreport/pull/121

Adjust tests

---

.drone.starlark
tests/unit/ConnectionTest.php
tests/unit/User/ManagerTest.php
tests/unit/User/UserEntryTest.php
vendor-bin/owncloud-codestyle/composer.json

like done in core https://github.com/owncloud/core/pull/36580
and apply latest drone starlark code changes
Note: there was no effect here on `.drone.yml`

Coding standard 2.0.0

---

.drone.starlark
.drone.yml

Issue https://github.com/owncloud/QA/issues/640

Update starlark code 20200208

---

vendor-bin/behat/composer.json

needed because of https://github.com/owncloud/core/pull/36999

[Tests-only] Bump guzzle for testing to 6.5

---

tests/acceptance/config/behat.yml

needed to run the extra tests from https://github.com/owncloud/core/pull/37006

[Tests-only] Run more core tests

---

composer.json
composer.lock

similar to core issue https://github.com/owncloud/core/issues/36676 and PR https://github.com/owncloud/core/pull/36677
Note: this is on top of PR #524

switch dependency from zendframework to laminas

---

.drone.starlark
.drone.yml
tests/acceptance/config/behat.yml

adjustments to make tests pass, that were added in https://github.com/owncloud/core/pull/37017

[Tests-only] make new core tests passing

---

CHANGELOG.md
appinfo/info.xml

Closes https://github.com/owncloud/user_ldap/issues/528

Merge back Release 0.15.1

---

.gitignore
tests/unit/CommandTest.php
tests/unit/Controller/ConfigurationControllerTest.php
tests/unit/Controller/WizardControllerTest.php
tests/unit/Group_LDAPTest.php
vendor-bin/behat/composer.json
vendor-bin/phpstan/composer.json

Part of https://github.com/owncloud/QA/issues/647

[Tests-Only] Implement phpunit v8

---

tests/acceptance/features/webUIUserLDAP/groupMembership.feature

Part of #570 
Hopefully this is the last fix needed.

[Tests-Only] Fix sharing step in groupMembership.feature

---

.drone.starlark
.drone.yml

- - https://github.com/owncloud/user_ldap/issues/578

[Tests-Only] Use openldap:1.3.0

---

CHANGELOG.md
appinfo/info.xml

Closes https://github.com/owncloud/user_ldap/issues/577

Merge back Release 0.15.2

---

.drone.starlark
.drone.yml

To match the change in core PR https://github.com/owncloud/core/pull/38077

Change TEST_EXTERNAL_USER_BACKENDS to TEST_WITH_LDAP

---

.drone.starlark
.drone.yml
.gitignore
sonar-project.properties

fix the starlark code for reduced ci after merge and sonarcloud
https://github.com/owncloud/QA/issues/649

[Tests-Only][CI] fix the starlark code for reduced ci after merge and sonarcloud

---

.drone.starlark

Issue https://github.com/owncloud/core/issues/38232

[tests-only] pin mini/mc docker to work-around broken 'latest'

---

.drone.starlark
.drone.yml
Makefile

Fixes #616 
Apply starlark changes like done in encryption PR 237
(I think that there will be more to do for some nightly jobs, but first this can be merged an we can see the results of the nightly tonight)

Adjust drone CI to fix issue 616

---

.drone.starlark
.drone.yml

Issue https://github.com/owncloud/encryption/issues/238

[tests-only] Do not define SONAR_PULL_REQUEST env vars on master CI

---

.drone.starlark
.drone.yml

mysql 5.5 is very old, mysql 5.7 is also no longer in the supported list https://doc.owncloud.com/server/10.6/admin_manual/installation/system_requirements.html
Test with mySQL 8.0, which is the official supported mySQL version.

[tests-only] Test with mysql 8.0

---

tests/acceptance/features/apiProvisioningLDAP/users.feature
tests/acceptance/features/apiUserLDAP/backupServerConnection.feature
tests/acceptance/features/apiUserLDAP/sharingLocalUserLdapUser.feature
tests/acceptance/features/cliProvisioning/users.feature
tests/acceptance/features/webUIProvisioning/users.feature
tests/acceptance/features/webUIUserLDAP/groupMembership.feature
tests/acceptance/features/webUIUserLDAP/paging.feature

like was done in core last week.
Fixes CI - part of issue https://github.com/owncloud/QA/issues/653

[tests-only] Specify skeleton in tests

---

lib/User_Proxy.php

Don't throw exception

---

css/settings.css
js/wizard/view.js
templates/part.wizard-groupfilter.php
templates/part.wizardcontrols.php

fix display errors in combination with other apps

---

appinfo/info.xml
lib/AppInfo/Application.php
lib/Command/InvalidateCache.php
lib/Group_LDAP.php
lib/Group_Proxy.php
lib/User_LDAP.php
lib/User_Proxy.php
tests/unit/Group_LDAPTest.php
tests/unit/User_LDAPTest.php

Link to https://github.com/owncloud/enterprise/issues/4533
The command will remove ALL the cache entries associated to the LDAP app.

Add a command to invalidate the LDAP cache

---

.drone.star
vendor-bin/phan/composer.json

1) Update to latest .drone.star code
2) Bump PHP phan to major version 5
Part of https://github.com/owncloud/QA/issues/696

Bump drone 20211107

---

tests/acceptance/features/bootstrap/UserLdapGeneralContext.php
tests/acceptance/features/bootstrap/UserLdapUsersContext.php
tests/acceptance/features/bootstrap/bootstrap.php

Related https://github.com/owncloud/QA/issues/694
- add strict type checking on acceptace test code
**note** this PR was generated by a automated script

[Tests-Only][full-ci] enforce strict type checking in acceptace tests code

---

templates/settings.php

Include a notice in the wizard for the known limitation with the recursive group membership
Ref https://github.com/owncloud/user_ldap/issues/755

Include a notice for the recursive group membership algorithm

---

.drone.star

There is nothing really interesting here, but it is good to keep the `.drone.star` CI code up-to-date with the latest in the activity app.

[tests-only] [full-ci] Update .drone.star code from activity app

---

.drone.star

Part of issue https://github.com/owncloud/QA/issues/818

[full-ci] [tests-only] Update CI

---

lib/Wizard.php

guessBaseDN: try to parse domain part from a user given in email syntax

---

tests/acceptance/features/apiUserLDAP/sharingLocalUserLdapUser.feature

This PR reverts back PR https://github.com/owncloud/user_ldap/pull/811
Fixes https://github.com/owncloud/user_ldap/issues/814

[tests-only][full-ci]revert back status code to 500

---

CHANGELOG.md
appinfo/info.xml
sonar-project.properties

Merge back Release 0.19.0

---

lib/Wizard.php
phpstan.neon

Fixes https://github.com/owncloud/user_ldap/issues/824

fix: strict comparison

---

CHANGELOG.md
appinfo/info.xml
sonar-project.properties

Merge back Release 0.19.1
