owncloud/user_ldap

lib/User/User.php
The uid might be empty if the mapped owncloud_username, eg. mail is empty. While admins should make   sure the attribute is always set the ldap admins are only human. Errors happen and we need to protect against user errer. In this case we should die hard, giving everyone a hint at what might be wrong, which is why I use assert(). It will throw an exception and prevent further desaster. As in overwriting the quota for all users ...
=> Prevent user with empty uid

lib/User/User.php, tests/User/UserTest.php
Expected behaviour with these changes:
* If both LDAP quota field and default LDAP quota are set:
* if the user has a value for the LDAP quota attribute, try to use that value as quota
* if the user doesn't have a value for the LDAP quota attribute or the value can't be parsed correctly, use the default LDAP quota.
* if the user doesn't have a value for the LDAP quota attribute or the value can't be parsed correctly, and the default LDAP quota can't be parsed correctly, use the ownCloud's default quota.
* If the LDAP quota field is empty and the default LDAP quota is set:
* go through the above case and consider the user doesn't have the LDAP quota attribute set.
* If the LDAP quota field isn't empty and the LDAP default quota isn't set:
* if the user has a value for the attribute, try to …
=> Correctly apply quota

templates/settings.php
Fixes https://github.com/owncloud/user_ldap/issues/53
@jvillafanez
=> Add tooltips to LDAP wizard special attributtes

lib/Group_Proxy.php
Some crashes happened due to the method not being implemented.
@PVince81
=> Fix missing method

lib/User/User.php
Log a message and try to set the email as null if it's duplicated, logging again if it isn't possible. Duplicated emails will be ignored.
=> Fix user import duplicated mails

appinfo/info.xml, lib/User/Manager.php, lib/User/User.php, lib/User_LDAP.php, lib/User_Proxy.php, tests/User/ManagerTest.php, tests/User/UserTest.php
Retrieves search attributes from LDAP based on the config and stores them alongside the user in the accounts table using the new search_attributes column.
Requires https://github.com/owncloud/core/issues/27850
@butonic @cdamken
=> Import search attributes into core account table for faster searching

lib/Command/CreateEmptyConfig.php
I had to remove the clause to being able to always set values via the
CLI. With this condition you can not configure the first group on the
CLI, without that condition you always get `s01` as a first prefix and
you are able to configure it on the CLI
Signed-off-by: Thomas Boerger <tboerger@owncloud.com>
=> Always set a proper prefix on CLI

lib/Connection.php
The current log is something like:
``Configuration Error (prefix ): either no password is given for theuser agent or a password is given, but not anLDAP agent.``
Afterwards it has the correct spaces like:
``Configuration Error (prefix ): either no password is given for the user agent or a password is given, but not an LDAP agent.``
=> Add missing spaces to log message

lib/Access.php, lib/User_LDAP.php, tests/AccessTest.php
While working on #28212 I was profiling the performance for user:sync and this actually made a measurable difference. The user:sync command already has explicit update logic. The update logic in checkPassword remains.
=> remove unneeded account updates

tests/.htaccess
Same as https://github.com/owncloud/core/issues/28343
Ref: https://github.com/owncloud/core/issues/28307
=> Only use IndexIgnore if mod_autoindex.c is enabled/loaded

README.md, lib/User/User.php, tests/User/UserTest.php
**Description**
Makes the time between needsRefresh configurable via app config option updateAttribuesInterval.
Default is still 86400 secons which is one day.
**Motivation and Context**
Modify the interval without changing the sourcecode to make the interval persistent when updating
**Types of changes**
- ~~Bug fix (non-breaking change which fixes an issue)~~
- ~~Breaking change (fix or feature that would cause existing functionality to change)~~
**Checklist:**
=> user_ldap: Makes the time between needsRefresh configurable

lib/LDAP.php
Now diagnostic will additionally log not only:
{"type":"SUMMARY","reqId":"2SbkuVM7SIi1AYznLWOr","time":"2017-09-03T18:25:20+00:00","remoteAddr":"::1","user":"admin","method":"GET","url":"\/octest\/index.php\/settings\/users","diagnostics":{"totalSQLQueries":7074,"totalSQLDurationmsec":101634.19699669,"totalSQLParams":12178,"totalEvents":**11044**,"totalEventsDurationmsec":**309342409.3241**7}}
But also:
{"type":"EVENT","reqId":"h4omRwYvlrurorofXIys","diagnostics":{"eventDescription":"**ldap_read(resource,cn=army994,ou=armies,dc=owncloud,dc=com,objectClass=*,array)**","eventDurationmsec":**416.74113273621**,"eventTimestamp":1504463311.8281}}
@butonic @felixboehm
=> Log LDAP calls as events for diagnostics (fix_user_access base)

lib/Command/CreateEmptyConfig.php
Adds an optional `configId` param to `occ ldap:create-empty-config`
new feature
It improves scriptability of ldap setups, eg for automated testing with multiple ldap servers
locally, juggling 7 ldap servers, writing a script that automatically sets up the connections
The configuration class and user_ldap does not yet use DI ... makes it hard to write a unit test. oh well
=> Allow specifying the prefix for occ ldap:create-empty-config

lib/User/Manager.php, lib/User/UserEntry.php
When no quota attribute has been configured and no quota default for ldap users, logging in a user will use `false` to set the quota, which becomes ` B`, an invalid quota oc treats as 0b. any existing quota that may have been set by the admin gets overwritten.
This pr only updates the quota of an account if it has been confugired and returns a non `false` value.
=> Do not set false quota on login

lib/User/Manager.php, tests/User/ManagerTest.php
fixes this
```
✗ sudo php occ user:sync "OCA\User_LDAP\User_Proxy"
If unknown users are found, what do you want to do with their accounts? (removing the account will also remove its data)
[0] disable
[1] remove
[2] ask later
> 1
Analyse unknown users ...
2 [-->-------------------------]An unhandled exception has been thrown:
Error: Class 'OCA\User_LDAP\Exceptions\DoesNotExsitOnLDAPException' not found in /mnt/c/Users/jfd/Repositories/oc/core/apps-repos/user_ldap/lib/User/Manager.php:197
Stack trace:
#0 /mnt/c/Users/jfd/Repositories/oc/core/apps-repos/user_ldap/lib/User_LDAP.php(196): OCA\User_LDAP\User\Manager->getUserEntryByDn('uid=zombie295,o...')
#1 [internal function]: OCA\User_LDAP\User_LDAP->userExists('8d9e8286-d23b-1...')
#2 …
```
=> fix typo in DoesNotExsitOnLDAPException

lib/Access.php, lib/User/UserEntry.php, tests/User/UserEntryTest.php
added test casoe with uuid ending in trimmable char .... this prevents the uuid from becoming 00000000-0000-0000-0000-000000000000.
also throws an exception the binary uuid could not be parsed. pack only gives a warning.
@patrickjahns @tomneedham this is rather critical as it may cause two or more users from being mapped to the same uuid ...
=> do not trim uuid

lib/User/Manager.php
without this the user sync will happily use a previously mapped dn to fetch a user entry and ignore any user filter
cc @tomneedham
=> use user filter when fetching user entry by dn

lib/User/Manager.php, lib/User_LDAP.php
fixes https://github.com/owncloud/user_ldap/issues/177 if core does not do the sync
=> pass password as it is needed by the encryption

lib/Command/ShowConfig.php, tests/CommandTest.php
for other commands we have the `--output` switch to be able to output the data as json
This switch would be also handy for user_ldap app, to be able to parse that output correctly. This is useful for automated tests
=> allow json output format

tests/acceptance/config/ldap-users.ldif
Core PR https://github.com/owncloud/core/pull/30798 used some different and longer group names in acceptance tests that check sharing autocompletion, because now there is a default minimum for that autocompletion lookup and so existing group and user names for tests need to be a decent length.
We can add those here, and also need to keep the other "grp1"... names that are used elsewhere in other acceptance tests. It should all pass with both sets of test groups existing - CI will know.
=> Add longer group names added in core 30798

lib/Command/CheckUser.php
because ldapUserCleanupInterval does not exist any more.
See core PR https://github.com/owncloud/core/pull/30805
and core issue https://github.com/owncloud/core/issues/30419
and user_ldap issue #179
=> Remove comment reference to ldapUserCleanupInterval

tests/acceptance/features/webUIUserLDAP/groupMembership.feature
The ``user_ldap`` acceptance tests actually have a fixed list of users and groups that exist at the start of each scenario. But if a test scenario depends on understanding the particular mix of names that exist (e.g. auto-complete) then it needs to know about the relevant users and groups that exist.
In core, I enhanced the auto-complete checks so they would complain if more entries are in the auto-complete list than expected. As a result, the test scenario here needs to know the group names that exist so it can decide what names should be in the auto-complete matches.
=> Tell groupMembership auto-complete test about the groups that exist

lib/User_LDAP.php, lib/User_Proxy.php
Fix https://github.com/owncloud/enterprise/issues/2459 by making the profile read-only for the displayname and email.
Consider this PR as **untested** unless told otherwise.
=> Displayname nor email won't be editable from the profile page

.drone.yml
After core https://github.com/owncloud/core/pull/31348 it is possible to run webUI acceptance tests from the common ``tests/acceptance/run.sh`` script, so do it.
=> Use acceptance test run.sh for webUI tests

tests/acceptance/config/behat.yml
we don't need to enable `PageObjectExtension` here, as its already enabled by `run.sh`
but we need the junit extension, as `run.sh` starts behat with `-f junit` and without configuring the path the extension will try to write to `/webuicore.xml`
=> fix behat extensions use

tests/acceptance/config/behat.yml, tests/acceptance/features/bootstrap/UserLdapGeneralContext.php
after https://github.com/owncloud/core/pull/32239 we can always use the remote version of occ by the testing app
=> always use occ by testing app

lib/User/Manager.php, lib/User_LDAP.php, lib/User_Proxy.php, tests/unit/User/ManagerTest.php, tests/unit/User_LDAPTest.php
Fix https://github.com/owncloud/enterprise/issues/2553
Checked against OC 10.0.9RC2. There shouldn't be any extra core requirement.
=> Restore avatar behaviour of OC 9.1

.gitignore, Makefile, README.md, lib/User/Manager.php, lib/User_LDAP.php, tests/unit/User_LDAPTest.php
When we try to login, we do a lookup on the LDAP server. Unfortunately when not found it just threw a basic exception which could be the same as connection error etc. So I swapped it to use the proper DoesNotExistOnLDAPException and catch this and not log it, but still log other exceptions.
=> Dont throw exception when user not found on ldap during login

.drone.yml
After recent core changes to the way the ``local_storage`` folder is created, this passes.
The test runner script can do everything it needs by using the testing app.
=> su-exec www-data is not needed for acceptance tests

lib/User/UserEntry.php
If the quota isn't set for the user, supress the "invalid quota" log message.
Superseds https://github.com/owncloud/user_ldap/pull/235
=> Jump over invalid quota message if quota isn't provided

tests/acceptance/features/webUIUserLDAP/groupMembership.feature
Fixes #313
Fix acceptance test steps that were changed in core.
```
Given * users have been created
``` 
to 
```
Given * users have been created with default attributes
```
Issue #313
=> Fix steps changed in core

Makefile, tests/acceptance/features/bootstrap/bootstrap.php
1. fixes https://github.com/owncloud/QA/issues/605
2. it should be possible to use `BEHAT_FEATURE` to specify a single file or tests
before that change running ` make test-acceptance-ldap` without `BEHAT_SUITE` would result in
```
[Behat\Testwork\Suite\Exception\SuiteNotFoundException]               
`acceptance` suite is not found or has not been properly registered. 
```
now running ` make test-acceptance-ldap` without `BEHAT_SUITE` is possible but `BEHAT_FEATURE` need to be specified. If non of both are specified the command will try to run all suites from the yml file
=> Fix acceptance tests

tests/acceptance/config/behat.yml
for suites that need it.
``WebDavPropertiesContext`` was created in core by:
https://github.com/owncloud/core/pull/34115
https://github.com/owncloud/core/pull/34124
=> Add WebDavPropertiesContext to behat.yml

tests/acceptance/features/cliProvisioning/users.feature
Related to issue #292 
Acceptance tests for checking if modifying the attributes is blocked when LDAP attributes are set for those.
=> Add tests for checking if admin can modify LDAP defined attributes

.drone.yml, tests/acceptance/config/behat.yml, tests/acceptance/features/bootstrap/bootstrap.php, tests/acceptance/features/webUIProvisioning/groups.feature, tests/acceptance/features/webUIProvisioning/users.feature
Related Issue #343
Add webUI acceptance tests for checking what can/cannot happen with respect to modifying attributes of LDAP users and groups
=> Add webUI Provisioning tests for ldap users and groups

.drone.yml
1) fixup the indent (lots of sections were indented by 3 and 5 chars instead of 2,4,6 like the "normal" parts)
2) sort the core  API acceptance test suite jobs into alphabetical order - to make it easier in future when checking these lists.
In preparation for adding new core acceptance test suites.
=> Refactor drone yml

.drone.yml, tests/acceptance/config/behat.yml, tests/acceptance/features/apiProvisioningLDAP/groups.feature, tests/acceptance/features/apiProvisioningLDAP/users.feature, tests/acceptance/features/bootstrap/UserLdapGeneralContext.php
Related Issue #343
Add API acceptance tests for checking what can/cannot happen with respect to modifying attributes of LDAP users and groups.
=> Add API provisioning tests for users and groups in ldap

tests/acceptance/features/webUIProvisioning/users.feature
#360 added webui related test for ldap users. But modifying email of user was missing.
Added tests for chaning email of ldap user.
=> Add webUI test for changing ldap user email

.drone.yml, tests/acceptance/config/behat.yml, tests/acceptance/config/ldap-users.ldif
Related issue #354
Add all remaining core test suites for testing in drone
Requires **https://github.com/owncloud/core/pull/34340** in the QA tarball
=> Add remaining core suites in user_ldap for testing

lib/User/Manager.php, lib/User_LDAP.php, lib/User_Proxy.php
Currently, a user cannot change his avatar. Even if ldap does not provide an avatar.
The handleRequest stuff cannot properly be used for methods that return a boolean.
=> reallow avatars to be changed if not provided by ldap

tests/acceptance/config/behat.yml
apiAuth tests need now the CORS context see https://github.com/owncloud/core/pull/34665
=> register CORS context

lib/Access.php, lib/Connection.php
the existing pagination code works correctly limit is 0. but when it is >0 it assumes that pagination should be disabled and always abandons all paged queries (which triggers the paging size to be set to 0 and immediately afterwards to the configured page size) This resets paged searches for eg edirectory netiq.
=> fix paging when limit is used

.drone.yml
Issue https://github.com/owncloud/core/issues/34787
disable integrity check during test runs
see other app changes ffor similar:
https://github.com/owncloud/user_management/pull/169
https://github.com/owncloud/password_policy/pull/213
to fix drone fails like:
https://drone.owncloud.com/owncloud/user_ldap/1293/395
=> disable integrity check because of QA tarball issue

appinfo/Migrations/Version20190315192717.php, lib/Configuration.php, lib/Helper.php, tests/unit/Controller/ConfigurationControllerTest.php
**Contains a migration - needs minor version bump for the app**
Make transition to new Wizard easier by
Before:
```
select configkey, configvalue from oc_appconfig where appid='user_ldap' and configkey  like 's01%';
+--------------------------------------+----------------+
| configkey                            | configvalue    |
+--------------------------------------+----------------+
| s01has_memberof_filter_support       | 0              |
| s01home_folder_naming_rule           |                |
| s01last_jpegPhoto_lookup             | 0              |
| s01ldap_agent_password               |                |
| s01ldap_attributes_for_group_search  |                |
| s01ldap_attributes_for_user_search   |                |
| s01ldap_backup_host                  |                |
| …
```
=> Config to json

.drone.yml, Makefile
=> Standardize CI scripts

js/wizard/configModel.js, js/wizard/view.js, js/wizard/wizardDetectorAvailableAttributes.js, js/wizard/wizardDetectorBaseDN.js, js/wizard/wizardDetectorFeatureAbstract.js, js/wizard/wizardDetectorPort.js, js/wizard/wizardDetectorSimpleRequestAbstract.js, js/wizard/wizardDetectorTestAbstract.js, js/wizard/wizardTabExpert.js, lib/Controller/ConfigurationController.php, lib/Controller/MappingController.php, lib/Controller/WizardController.php
Do some TODOs and fix one FIXME 
Basically renames 
`ldap_serverconfig_chooser` into `id` to match https://github.com/owncloud/user_ldap/pull/210
`ldap_clear_mapping` into `subject`
=> Rename controller args and json keys

lib/Helper.php
Discovered while testing https://github.com/owncloud/user_ldap/pull/407
Config deletion didn't remove it from dropdown because deleteServerConfiguration had false negative result.
=> Fix false negative result when deleting a server configuration

appinfo/Migrations/Version20190315192717.php, js/wizard/configModel.js, lib/Command/TestConfig.php, lib/Configuration.php, lib/Connection.php, lib/Controller/ConfigurationController.php, lib/Wizard.php, tests/integration/Lib/IntegrationBackupServer.php, tests/integration/Lib/IntegrationTestBackupServer.php, tests/unit/Controller/ConfigurationControllerTest.php, tests/unit/WizardTest.php
This is a followup for https://github.com/owncloud/user_ldap/pull/393
We can encode arrays directly to json and do not use CR/LF as a separator. 
Before
```
"ldapBase":"dc=firstbase,dc=com/ndc=secondbase,dc=com"
```
After 
```
"ldapBase":"[
"dc=firstbase,dc=com",
"dc=secondbase,dc=com"
]
```
Note that the part splitting these values when they are coming from the wizard is still in place.
Additionally, the config options notation has been unified to pascalCase.
E.g. 
before **$configuration->ldap_host** or **$configuration->ldapHost** could be used so the code was a bit messy
This PR removes **$configuration->ldap_host** notation support and makes the frontend responsible for underscore <-> pascalCase transformation.
=> Store arrays as arrays, do not use newline as a separator

tests/acceptance/features/apiProvisioningLDAP/users.feature, tests/acceptance/features/cliProvisioning/users.feature, tests/acceptance/features/webUIProvisioning/users.feature
small improvements to the testing code
=> Email change test improvements

.drone.yml, tests/acceptance/config/behat.yml
Fixes #413 
Similar to https://github.com/owncloud/core/pull/35170
Add CI for:
```
apiAuthOcs
apiShareManagementBasic
apiWebdavLocks2
```
Note, we do not run the core provisioning suites here, so there is no need to add the new `apiProvisioningGroups-v1` and `apiProvisioningGroups-v2` suites.
=> Split long-running api acceptance suites

js/wizard/configModel.js
Previous commit from master (16f229a8fb6515f86bdd9bdbd99d28e0fadd4940) has the wizard broken due to the mappings introduced in 7277bf0d6ac92be60bb84520c0c358187218b226 .
This commit fixes the issue. The wizard works again now.
=> Fix wizard by translating keys (missing code)

lib/Access.php, lib/User/Manager.php, tests/acceptance/features/apiProvisioningLDAP/groups.feature, tests/acceptance/features/apiUserLDAPConnection/groupFilter.feature, tests/acceptance/features/webUIProvisioning/groups.feature, tests/acceptance/features/webUIUserLDAP/groupMembership.feature
This PR changes the way the LDAP app creates the mapping entries. I am still evaluating the possible effects of this change. 
Essentially, this allows new LDAP logins to attempt to reuse existing oc_accounts entries that match the resolved username attribute AND have backend = User_Proxy.
This fixes when admins mistakenly delete the user mapping, and logins then create new accounts.
It also allows auto provisioned users with shiboleth me moved over to and LDAP server and continue using owncloud, simply by updating their backend string: `UPDATE oc_accounts SET backend = 'OCA\User_LDAP\User_Proxy' WHERE backend = 'OCA\User_Shibboleth\UserBackend';`
Edit: UPDATED. Now it will fail, and kill crazy names - but if you set oc_appconfig user_ldap `reuse_accounts` then a new mapping is allowed to …
=> Reuse existing LDAP accounts if available

tests/acceptance/config/ldap-users.ldif
This group are now used in core tests, so easy to add them here so that the same tests will run in user_ldap
=> add emoji group in the ldif file to be imported at start of tests

lib/LDAP.php
Prevent failure with the backup server if no port is suplied.
Related to https://github.com/owncloud/enterprise/issues/2756
=> Include port only if there is port

appinfo/info.xml
Fixes https://github.com/owncloud/core/issues/35345
https://github.com/owncloud/user_ldap/pull/248 removed the job but left an entry in appinfo
=> Remove no longer existing job from appinfo

.drone.yml, tests/acceptance/config/behat.yml
Split core webUI tests into two parts to reduce drone job time.
https://github.com/owncloud/user_ldap/issues/422
🤖
=> split core webUI tests into two parts

.drone.yml, tests/acceptance/features/webUIUserLDAP/groupMembership.feature, tests/acceptance/features/webUIUserLDAP/loginUsingEmailAddress.feature
This test guarantee that the ```user_ldap``` app runs correctly against the last released core version.
Part of https://github.com/owncloud/QA/issues/611
=> user_ldap app test against latest tarball

.drone.yml, tests/acceptance/config/behat.yml, tests/acceptance/features/apiUserLDAPSharing/sharingLocalUserLdapUser.feature
Fixes issue #438 
The 2nd commit fixes https://drone.owncloud.com/owncloud/user_ldap/1705/1025
```
--- Failed scenarios:
/var/www/owncloud/server/tests/acceptance/features/apiFederation/federated.feature:555
/var/www/owncloud/server/tests/acceptance/features/apiFederation/federated.feature:575
60 scenarios (58 passed, 2 failed)
725 steps (721 passed, 2 failed, 2 skipped)
```
by properly starting a separate federated server during drone testing. That makes the trusted server tests work properly.
=> Add WebUIAdminSharingSettingsContext for acceptance tests

appinfo/info.xml, appinfo/register_command.php
if we want not to loose compatibility with 10.2
=> Hotfix #447

lib/Connection.php, lib/User/Manager.php, lib/User_LDAP.php
Fixes https://github.com/owncloud/enterprise/issues/3496
This PR adds a catch blog for expected exceptions in password check, to not show internal error for users.
`ldap_connect` only applies syntactic checks for given parameters, does not contact the server. In our implementation, as far as I see, we assume the server will be available if a request passes from this check. I clarified this situation with comment lines for further usages.
=> add a catch blog for expected exceptions in password check

tests/acceptance/config/behat.yml
Issue #463 
core PR https://github.com/owncloud/core/pull/36321 added core test scenarios that need `WebDavPropertiesContext`
Add it here in `user_ldap` also, so that core CI can pass.
=> Add WebDavPropertiesContext to apiWebdavOperations

tests/acceptance/config/behat.yml
Part of issue #422 
The second part of the core webUI tests had 42 scenarios, the first part had only 8 scenarios.
`webUISharingExternal` has about 30 scenarios enabled for running on `user_ldap` - so leave that as the only suite in `webUICore2`
This will reduce a bit the time taken for the `webUICore2`, which will help to (sometimes) reduce the overall elapsed time for the `user_ldap` drone runs.
=> Balance webUI core tests

.drone.starlark, .drone.yml, tests/acceptance/config/behat.yml, vendor-bin/php_codesniffer/composer.json
Cherry-pick "recent" drone CI changes into the `release-0.14.0` branch so that it can successfully run current CI.
From CI-related PRs:
#448 
#450 
#452 
#454 
#455 
#458 
#459 
#464 
#462 
Then disable running `phan` in CI, because the "hotfix" PR #449 that is in the release branch has temporarily put back code that does not pass `phan`
=> Drone for 0.14.0 branch

tests/acceptance/config/behat.yml
https://github.com/owncloud/core/pull/36391 new test scenario in apiVersions needed WebDavPropertiesContext. So we also need it here in `user_ldap` when running apiVersions suite from code.
=> Adjust behat.yml apiVersions due to core 36391

.drone.starlark, .drone.yml
Currently we run all the core tests with LDAP. In encryption app we run with encyption app enabled. But in more realistic live production environment, the system might have both LDAP and encryption at the same time. To test such scenarios this PR adds the drone configuration for running all the core tests with LDAP and encryption  enabled at the same time.
Related https://github.com/owncloud/qa-enterprise/issues/141#issuecomment-555869863
=> Add drone setup for running tests with ldap and encryption enabled

lib/Access.php, lib/User/Manager.php, lib/User_LDAP.php, tests/unit/User/ManagerTest.php, tests/unit/User_LDAPTest.php
I'm reusing an orphaned method `OCA\User_LDAP\User\Manager::dnExistsOnLDAP` to search the missing DN by UUID mapping
Please note that **UUID Attribute for Users** aka  `ldap_expert_uuid_user_attr`  should have really unique values.
0. Prepare the following structure:
```
ou=parent,dc=owncloudqa,dc=com
ou=unit1,ou=parent,dc=owncloudqa,dc=com
ou=unit2,ou=parent,dc=owncloudqa,dc=com
```
1. Put users into  `ou=unit1,ou=parent,dc=owncloudqa,dc=com`
2. Setup user_ldap app:
add `ou=parent,dc=owncloudqa,dc=com` as a `ldap_base_users` 
In the expert tab add `UUID Attribute for Users` e.g. to be `uid`
3.  Execute `php occ user:sync -m remove "OCA\User_LDAP\User_Proxy"`
4. Login as any Ldap user, upload a new file and logout
5. **Move** this user from `ou=unit1,ou=parent,dc=owncloudqa,dc=com` to …
=> Detect a new DN by UUID attribute

.drone.starlark, .drone.yml
We added nightly tests that run core tests with both user_ldap and encryption available.
Some scenarios fail, e.g.
https://drone.owncloud.com/owncloud/user_ldap/2008/164/13
```
--- Failed scenarios:
/var/www/owncloud/testrunner/tests/acceptance/features/apiTrashbin/trashbinFilesFolders.feature:187
/var/www/owncloud/testrunner/tests/acceptance/features/apiTrashbin/trashbinRestore.feature:231
/var/www/owncloud/testrunner/tests/acceptance/features/apiTrashbin/trashbinRestore.feature:232
/var/www/owncloud/testrunner/tests/acceptance/features/apiTrashbin/trashbinRestore.feature:237
/var/www/owncloud/testrunner/tests/acceptance/features/apiTrashbin/trashbinRestore.feature:254
66 scenarios (61 passed, 5 failed)
786 steps (751 passed, 5 failed, 30 skipped)
```
These are scenarios that already …
=> Add skipOnEncryption filter tags to pipelines with encryption

Makefile
Issue #478 
This will need core PR https://github.com/owncloud/core/pull/36504 also.
In addition to specifying the "usual" filter tags when doing `test-acceptance-core-*`, also append any tags that have been specified in `BEHAT_FILTER_TAGS`.
This allows drone CI (or the user) to set `BEHAT_FILTER_TAGS`  to specify any extra tags they need for a special run of the tests (e.g. in a setup with encryption) and to also get the "usual"  filter tags that are specified in `Makefile`
=> Append BEHAT_FILTER_TAGS to default tags when running core acceptance tests

composer.json, tests/acceptance/config/behat.yml, tests/acceptance/features/apiProvisioningLDAP/groups.feature, tests/acceptance/features/apiProvisioningLDAP/users.feature, tests/acceptance/features/apiUserLDAP/moveUser.feature, tests/acceptance/features/apiUserLDAPConnection/backupServerConnection.feature, tests/acceptance/features/apiUserLDAPConnection/groupFilter.feature, tests/acceptance/features/apiUserLDAPConnection/serverConnection.feature, tests/acceptance/features/apiUserLDAPSharing/sharingLocalUserLdapUser.feature, tests/acceptance/features/bootstrap/UserLdapGeneralContext.php, tests/acceptance/features/bootstrap/UserLdapUsersContext.php, tests/acceptance/features/cliProvisioning/users.feature, tests/acceptance/features/webUIProvisioning/groups.feature, tests/acceptance/features/webUIProvisioning/users.feature, tests/acceptance/features/webUIUserLDAP/avatar.feature, tests/acceptance/features/webUIUserLDAP/changingDisplayName.feature, tests/acceptance/features/webUIUserLDAP/changingPassword.feature, tests/acceptance/features/webUIUserLDAP/groupMembership.feature, tests/acceptance/features/webUIUserLDAP/loginUsingEmailAddress.feature, tests/acceptance/features/webUIUserLDAP/paging.feature
It was a bit annoying to interact with zend-ldap from user_ldap tests.
Setups and configuration for ldap-connection has been migrated to core tests!
=> Migrate ldap connection and configurations from user_ldap tests to core tests

tests/acceptance/features/bootstrap/UserLdapGeneralContext.php, tests/acceptance/features/cliProvisioning/userSync.feature
- Adds test for `user:sync` of a particular user.
- On top of https://github.com/owncloud/core/pull/36790/files
https://github.com/owncloud/core/issues/33293
=> add user sync tests

tests/acceptance/features/cliProvisioning/userSync.feature
Acceptance tests added for `user:sync` command covering:
- defalt full users sync
- sync a local user
https://github.com/owncloud/core/issues/36597
https://github.com/owncloud/core/issues/33293
- :robot:
=> [Test_Only] Added acceptance test for single/multiple user:sync

tests/acceptance/features/cliProvisioning/userSync.feature
Acceptance tests added for `user:sync` command covering:
- sync a user that is a substring of some other LDAP user
- sync a user that is a substring and superstring of some local user
https://github.com/owncloud/core/issues/36597
https://github.com/owncloud/core/issues/33293
- :robot:
=> [Tests-Only] Added acceptance tests for user:sync command with super/sub-strings in user usernames

tests/acceptance/features/bootstrap/UserLdapGeneralContext.php, tests/acceptance/features/cliProvisioning/userSync.feature
Added acceptance test for occ command `user:sync` for a non-existing user
- Reproduces https://github.com/owncloud/user_ldap/issues/515
- Part of https://github.com/owncloud/core/issues/36597
=> [Tests-Only] Added acceptance test for user:sync with non-existing user

Makefile
I was doing `make clean` in this app and realised that it was not removing the `vendor` stuff like is the behaviour of `make clean` in the other apps.
Adjust the `clean` Makefile target to be like other apps.
=> fix make clean so it cleans vendor

composer.json
It was accidentally removed in PR #495 
A new `composer.lock` was not generated, so the removal had no real effect (yet).
I noticed it in https://github.com/owncloud/user_ldap/pull/523#issuecomment-591516241
Note: after putting this back, I will then make another PR to switch to `laminas-ldap`
=> Put back zend-ldap dependency

.drone.starlark, .drone.yml, tests/acceptance/config/behat.yml
`webUICore1` ends up running 74 scenarios and can sometimes take 2 hours to run.
e.g. https://drone.owncloud.com/owncloud/user_ldap/2308/236/21
Split into 3 parts. This will help getting user_ldap CI finished in less elapsed time.
=> Split webUICore pipelines into more parts

tests/acceptance/features/apiUserLDAP/specialUsernames.feature
PR #490 allowed `+` in LDAP usernames. There are a variety of valid characters in valid ownCloud usernames. Any of those should work when they come from LDAP.
We currently run the core acceptance tests with LDAP enabled. When run in that environment, they create the user(s) in LDAP, sync them and run the test scenario. But those tests mostly use "easy" usernames. The ones that check the "edge case" usernames are specifically using the provisioning API and not going via LDAP.
This PR adds a specific scenario to the LDAP suite that creates "edge case" usernames in LDAP and checks that the user can do the basic upload/download/delete operations.
=> Add scenario to check a variety of user names in LDAP

composer.lock
```
composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
- Updating laminas/laminas-zendframework-bridge (1.0.2 => 1.0.3): Loading from cache
Writing lock file
Generating autoload files
```
=> Updating laminas/laminas-zendframework-bridge (1.0.2 => 1.0.3)

tests/acceptance/features/apiProvisioningLDAP/userSync.feature
Add a test scenario for https://github.com/owncloud/core/pull/36428 that added an API for single-user sync to an authentication back-end (in this case LDAP).
Note: There could be more test scenarios for changing attributes in LDAP (e.g. display name or email address) and then syncing a single user and verify that the changed attribute is synced to ownCloud. Those need some code added that will do those things on the LDAP server without auto-syncing the changes etc. So I will make an issue to do that later. #563 
For now, it is nice to see that this simple single-user sync scenario works.
=> User sync with API

tests/acceptance/features/apiProvisioningLDAP/userSync.feature
:heavy_check_mark: tests scenarios for single user sync using OCS API are added
Fixes #563
=> [Tests-Only] Added test scenarios for single user sync using OCS API

composer.lock
```
composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
- Updating laminas/laminas-zendframework-bridge (1.0.3 => 1.0.4): Loading from cache
Writing lock file
Generating autoload files
```
This is the last dependency bump that is waiting.
=> Updating laminas/laminas-zendframework-bridge (1.0.3 => 1.0.4)

lib/Access.php, tests/integration/Lib/IntegrationTestPaging.php, tests/integration/setup-scripts/createExplicitUsers.php
Commit https://github.com/owncloud/user_ldap/commit/f4dc061a22af1a04bdbcfbe859dec277911e0ba9#diff-082c8dddc0cb46139a939a52fae88490R1959-R1960 removed user_ldap app capability to refetch cookie for continued paged search. This PR brings functionality back as it is required for correct handling of search with cookies - https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/manage/how-ldap-server-cookies-are-handled.
Fixes https://github.com/owncloud/enterprise/issues/3731
=> Reissue search in case of missing cookie in continued paged search

Makefile
PR https://github.com/owncloud/core/pull/37616 removed the `TestAlsoOnExternalUserBackend` tag from core features/scenarios.
Do not filter by that tag any more. Scenarios that are not relevant for LDAP are all tagged with `skipOnLDAP`
=> [Tests-Only] Remove unneeded TestAlsoOnExternalUserBackend tag

.drone.starlark, .drone.yml
run only smoke tests in ci for WebUI tests.
Fixes https://github.com/owncloud/user_ldap/issues/583
**This will require https://github.com/owncloud/core/pull/37630 to merge before nightly run to pass.**
=> [Tests-Only] only run smoke tests in CI

.drone.starlark, .drone.yml
Issue #578 
Remove the offending `HOSTNAME`env var in CI. Use the latest osixia/openldap
See similar fix in https://github.com/owncloud/phoenix/pull/3738
=> [Tests-Only] Use latest osixia/openldap in CI

.drone.starlark, .drone.yml
https://drone.owncloud.com/owncloud/user_ldap/2679/28/9
```
php occ ldap:test-config "LDAPTestId"
In Connection.php line 532:
[OCA\User_LDAP\Exceptions\BindFailedException]  
ldap:test-config <configID>
```
https://drone.owncloud.com/owncloud/user_ldap/2679/28/3
```
latest: Pulling from osixia/openldap
```
But it is often slow these days.
1) In the `configure-app` step we can wait for LDAP to come up. That should help when the LDAP docker image was slow to pull and start.
2) do the same wait for LDAP in the integration test pipelines
Part of issue #591
=> Wait for LDAP in CI

templates/part.wizard-loginfilter.php
Adds a warning that this config is not effective if strict checking is not enabled. Requires  https://github.com/owncloud/core/pull/37569
=> Add warning for disabling email login regarding strict login check

lib/Access.php, lib/Group_LDAP.php, lib/Group_Proxy.php, lib/User_LDAP.php, lib/User_Proxy.php, tests/integration/AbstractIntegrationTest.php, tests/integration/Lib/IntegrationTestPagingMultipleBase.php, tests/integration/setup-scripts/createExplicitUsers.php
When multiple base dns are configured the `AllUsersIterator` uses pages of 500 to page through the ldap results. It literally provides limit and offset:
https://github.com/owncloud/core/blob/d2697818a682904a13ba8d18e96411722853dd8a/lib/private/User/Sync/AllUsersIterator.php#L40-L47
That confuses the internal parralel seach cookie handling:
1. the first base dn tree only contains ... say 3 results.
2. the second base dn tree contains 1000
the first one will have no further results after the first page, causing the search to be abandoned -> which means all cookies are removed. even for the second base dn tree.
while that shouldn't matter, the next page starts with offset 500.
again, the first base dn tree has no results, abandoning the search and deleting all cookies ... so the sync has no …
=> Disable parallel paginated search for multi base dn on subsequent pages

.drone.starlark, .drone.yml, composer.json, composer.lock, vendor-bin/behat/composer.json
Issue https://github.com/owncloud/core/issues/38067
See issue for details - `behat` acceptance tests need to use PHP  7.4 for the dependencies to sort themselves out with composer 2.0
=> Adjust PHP dependencies for composer 2.0

lib/User_Proxy.php
I noticed that when sync'ing LDAP users with a quota of "0", they were stored with a quota of NULL. The reason is that there's a soft comparison here:
```
protected function walkBackends($uid, $method, $parameters) {
$cacheKey = $this->getUserCacheKey($uid);
foreach ($this->backends as $configPrefix => $backend) {
$instance = $backend;
if (!\method_exists($instance, $method)
&& \method_exists($this->getAccess($configPrefix), $method)) {
$instance = $this->getAccess($configPrefix);
}
if ($result = \call_user_func_array([$instance, $method], $parameters)) {
$this->writeToCache($cacheKey, $configPrefix);
return $result;
}
}
return false;
}
```
So when call_user_func_array returns "0" it is considered "false", the value is not cached nor returned, and the method returns "false".
Just adding …
=> Fixed read LDAP attribute value 0 returned as null

.drone.starlark, .drone.yml
Any core test scenario that is tagged `@app-required` is a test scenario that needs some non-core app to be installed and enabled. To run those scenarios requires that CI have code to install and enable the needed app(s).
For pipelines that do a general run of core scenarios, skip those scenarios.
=> [tests-only] skip core app-required scenarios

.drone.starlark, .drone.yml
Fixes issue #616 
The nightly needs to be run against `daily-master-qa` because some changes in encryption depend on core changes that are only in core master.
=> [tests-only] Run nightly encryption tests with daily-master-qa

.drone.starlark, .drone.yml
This reverts commit 3ce036d50e66c9de9e7521d8a8d9d821e71abe5f.
Fixes #620 
Put CI back the way it was before PR #618 had to stop running nightly CI against `latest`
=> [tests-only] Revert "Run nightly encryption tests with daily-master-qa"

tests/acceptance/features/bootstrap/UserLdapGeneralContext.php, tests/acceptance/features/bootstrap/UserLdapUsersContext.php
The `Zend` libraries changed their name to `Laminas` some time ago. `Laminas` put in place backward-compatible code. But it is "a good thing" to update the name some time = now that I noticed.
=> Replace Zend with Laminas

lib/Configuration.php
Filter special characters like `\r\n` to prevent Server Side Request Forgery (SSRF) attacks.
=> Security: filter special characters from password field

lib/User/Manager.php
This prevents firstLoginAccomplished log entries get written each time as a user logs in under certain circumstances (log level...).
=> Only set USER_PREFKEY_FIRSTLOGIN to '1' on first login

lib/Configuration.php
=> Just strip "low" chars, but don't do anything else

.drone.star, tests/acceptance/features/webUIProvisioning/users.feature, tests/acceptance/features/webUIUserLDAP/avatar.feature, tests/acceptance/features/webUIUserLDAP/changingDisplayName.feature
core PR https://github.com/owncloud/core/pull/39027 made some acceptance test steps consistently say "on the webUI"
1) This PR adjusts them in user_ldap feature files.
Fixes CI  fails like https://drone.owncloud.com/owncloud/user_ldap/3351/58/12
"FeatureContext has missing steps. Define them with these snippets:..."
2) Same as https://github.com/owncloud/admin_audit/issues/377 - fix the drone starlark so that `savePublicShare.feature` passes. The same starlark code changes as in https://github.com/owncloud/admin_audit/pull/378
=> [tests-only] [full-ci] Adjust acceptance test steps that changed in core PR 39027

lib/User/Manager.php
GitHub is reporting a conflict in PR #658 for file `lib/User/Manager.php`
That was changed in master by PR #652 
Maybe if we backport that to the `release-0.15.3` branch then the conflict will go away?
Note: PR #652 will not be in either release 0.15.3 or release 0.15.4 - this is just trying to get rid of the reported conflict so that we can merge PR #652
=> [0.15.3 branch] only set USER_PREFKEY_FIRSTLOGIN to '1' on first login

CHANGELOG.md, img/exclamation-triangle-solid.svg
=> change color of warning sign

.drone.star, Makefile
The latest changes to the `owncloudci/php` image have removed node, npm and yarn. So checks for those (and composer) in `Makefile` are removed here because, depending on the make target, some of the tools may not be needed, and depending on the docker image used in CI, some of the tools may not exist.
=> [tests-only] [full-ci] Update CI .drone.star and Makefile

tests/acceptance/features/webUIProvisioning/groups.feature
Core PR https://github.com/owncloud/core/pull/39305 added the test step:
```
When the administrator tries to add user "xxx" to group "yyy" using the webUI
```
This step allows us to test trying to add a user to an LDAP group, when we expect that it should not be possible. This PR makes use of the test step.
Previously the User Management UI "went through the motions" of adding a user to an LDAP group, but actually the action did not really happen on the server. Since core PR https://github.com/owncloud/core/pull/39262 the core user management UI no longer actually lets the user be added to an LDAP group. user_ldap CI has been failing:
```
runsh: Total unexpected failed scenarios throughout the test run:
webUIProvisioning/groups.feature:70
webUIProvisioning/groups.feature:85
Scenario: …
```
=> [tests-only] [full-ci] Adjust test scenarios that try to add a user to an LDAP group

.drone.star, phpunit.xml, sonar-project.properties, vendor-bin/behat/composer.json
1) switch to using PHP 7.4 for PHP unit tests with coverage (there is sometimes a problem generating coverage with PHPunit9 and PHP 7.3 and something in our combinations of dependencies... - we can easily avoid that, PHP 7.3 is about to end security support anyway...)
2) Migrate `phpunit.xml` with the command:
`../../lib/composer/bin/phpunit --migrate-configuration`
3) use phpunit 9 in acceptance test dependencies. That will fix failures running core tests like:
https://drone.owncloud.com/owncloud/user_ldap/3512/79/17
```
Fatal error: Call to undefined method PHPUnit\Framework\Assert::assertMatchesRegularExpression() (Behat\Testwork\Call\Exception\FatalThrowableError)
```
=> [tests-only] [full-ci] Bump tests to phpunit9

lib/Group_LDAP.php, tests/unit/Group_LDAPTest.php
For nested groups, this was a problem because the group filter could
remove the nested group, so we couldn't check the memberof attribute of
the nested group and we couldn't go upwards in the group tree.
GroupA contains GroupB, and GroupB contains User1. If the group filter
contains just GroupA (not GroupB), checking the "memberof" of User1
would return no group. This PR fixes this by returning GroupA, which is
part of the group filter (if the "nested groups" checkbox is active)
----
Related to https://github.com/owncloud/enterprise/issues/4754
1. In the AD create GroupA; inside GroupA create GroupB; inside GroupB create some users
2. Ensure the AD has additional users and groups
3. Configure the user_ldap app to connect to the AD
1. User filter is something like …
=> When checking memberof, apply the group filter after getting all groups

.drone.star
Those need special setup, which is done in core. We don't need to run those in app test pipelines.
=> [tests-only] skip dbConversion tests

.drone.star
Similar to https://github.com/owncloud/encryption/pull/316 and https://github.com/owncloud/encryption/pull/318
And I had too shorten various pipeline names to meet the 50-character limit.
Various LDAP+encryption pipelines fail against "latest". I will be good to test against 10.9.1RC1 and confirm that the issue is fixed.
This PR needs to be reverted after 10.9.1 is released and updated if there is an other RC
Related to encryption issue https://github.com/owncloud/encryption/issues/315
=> [tests-only] Test against 10.9.1RC1

.drone.star
10.9.1RC2 tarballs are now available, so use them.
Note: many of the pipelines run in nightly CI. So this needs to be merged, and we will get results overnight.
=> [tests-only] [full-ci] Test against 10.9.1RC2

.drone.star
Part of issue https://github.com/owncloud/encryption/issues/317
I reverted the 3 commits from PRs #709 and #705  in reverse order:
```
$ git checkout -b test-against-core-latest
Switched to a new branch 'test-against-core-latest'
$ git revert 36247291dbff17cd6e4d989a04d2d0449f45b734
[test-against-core-latest adaeee05] Revert "Test against 10.9.1RC2"
1 file changed, 15 insertions(+), 15 deletions(-)
$ git revert 5bbfe5bba825fb59fe60ae2b4d8102364cd2cfcb
Auto-merging .drone.star
[test-against-core-latest 24ee746a] Revert "Test against 10.9.1RC1"
1 file changed, 15 insertions(+), 15 deletions(-)
```
=> Test against core latest

CHANGELOG.md, lib/Access.php, lib/User/UserEntry.php, tests/unit/User/UserEntryTest.php
With Oracle eDirectory we sometimes get a GUID as binaray where our code would normally expect a string.
https://github.com/owncloud/enterprise/issues/4686
=> Decode binary guid

.drone.star, tests/acceptance/features/webUIProvisioning/groups.feature
Add tests to demonstrate the current behavior of the member count of LDAP groups on the User Management UI.
The member count is shown as zero.
Related issue: https://github.com/owncloud/enterprise/issues/4957
These tests can be a place for developers to start sorting this out - modify the tests to expect whatever is the required behavior, then get themj to pass.
The 2nd commit increases the number of pipelines for core-apiAll, in order to reduce the elapsed run-time. Issue #713
=> [tests-only] Test member count of LDAP group on webUI

composer.json, composer.lock, tests/acceptance/features/webUIProvisioning/groups.feature
This PR commits the `allow-plugins` section for `composer.json` so that it is there for anyone who updates to composer `2.2`.
The 2nd commit adjusts test scenarios for issue #716 - that gets all CI green.
Part of https://github.com/owncloud/QA/issues/723
Note: This PR is created with a script. If there is any unexpected case in it, I will update manually.
=> [full-ci] Add composer allow-plugins

tests/acceptance/features/bootstrap/UserLdapGeneralContext.php
Due to the changes made by PR https://github.com/owncloud/core/pull/39927/files in function `addUserToCreatedUsersList` few tests were failing this PR fixes that
Fixes: https://github.com/owncloud/user_ldap/issues/735
=> [tests-only][full-ci]Fix failing acceptance tests

phpunit.xml
This PR moves unit tests into tests/unit folder. And also tidy up the `phpunit.xml` to make standard format for all oc-apps as much as possible.
- Part of https://github.com/owncloud/impersonate/issues/198
=> [tests-only][full-ci]Tidy up the phpunit xml file `user_ldap` app

lib/Access.php, lib/Attributes/ConverterException.php, lib/Attributes/ConverterHub.php, lib/Attributes/GUIDConverter.php, lib/Attributes/IConverter.php, lib/Attributes/SIDConverter.php, lib/User/UserEntry.php, tests/unit/Attributes/ConverterHubTest.php, tests/unit/Attributes/GUIDConverterTest.php, tests/unit/Attributes/SIDConverterTest.php, tests/unit/User/UserEntryTest.php
Refactor code to allow conversion of binary attributes.
Previously only the "objectguid" and "guid" were being handled. Other attributes such as "objectsid" weren't. The refactor makes adding support for more binary attributes easier just by creating the converter and registering it in the converter hub.
For now, the 3 mentioned binary attributes are supported and they'll show the expected string representation. More can be added if needed.
Ref https://github.com/owncloud/user_ldap/issues/759
=> Binary converter

CHANGELOG.md, lib/User/UserEntry.php
Trimming on binary could potentially remove control-characters which are actually part of the binary attribute value.
=> Only trim on the string representation of an attribute

vendor-bin/behat/composer.json
Due to changes in core with this PR https://github.com/owncloud/core/pull/40619. Certain Apps requires to have a package `json-assertion` which was added in core. This PR adds the required package.
https://github.com/owncloud/QA/issues/800
=> [full-ci][tests-only]Added `json-assert` library to `user_ldap` app

lib/Access.php, lib/User/Manager.php, lib/Wizard.php, phpstan.neon
Fixes #777 
Some things have improved in phpstan.
Removed `phpstan-ignore-line` in a few places - those things are no longer reported as false positives - good.
Removed unused `checkHost()` function (phpstan noticed that this is unused)
The text of one of the ignored errors changed.
=> [full-ci] Fixup code reported by phpstan 1.10.1

.drone.star
For latest stable oc10 we still require the selection of the `encryption type masterkey`. since this was removed from the https://github.com/owncloud/user_ldap/commit/e9c3f1048ef02320759fbf205e1c0835ecc89dfd this PR. This PR reverts only the command to section type of encryption in latest nightly run with user_ldap and encryption.
***NOTE:This might fail when the master becomes the latest and at that time we can remove the selection of the encryption-type.***
More details can be found here:
https://github.com/owncloud/encryption/issues/393#issuecomment-1493280016.
https://github.com/owncloud/user_ldap/issues/780
=> [tests-only][full-ci]Reverted the selction for encription type master-key

lib/Connection.php
Add condition in `doConnect` for verifying network timeout is set.
Removing the `Network Timeout` value in the Advanced tab of the LDAP wizard is breaking the LDAP configuration with no hints whatsoever of what is wrong. There is no check in place in the WebUI to force the use of this option so we should add a condition to check if this is set when calling `doConnect`.
Manually by removing the `Network Timeout` value in the Advanced tab of the LDAP wizard and checking the LDAP configuration is still healthy.
=> Add condition in `doConnect` for checking network timeout is set

tests/acceptance/features/bootstrap/UserLdapGeneralContext.php
This PR removes the redundant param that was removed by core PR: https://github.com/owncloud/core/commit/db5434574a3ba96621550c18bfce25c804d7cd8b#diff-53ecaebb4552a8c12cb891ca32d9879923ec2d0226afeda7e559b9f631a1300c
Part of: https://github.com/owncloud/QA/issues/808
=> [tests-only] Remove redundant parameter

lib/Group_LDAP.php
Fix typo in the comments. The actual key is "displayName"; using "displayname" (full lowercase) won't work properly and the displayname would be ignored.
There is no change in the code since it has the right key and it already works.
=> Fix typo in comment. Make it less confusing

.drone.star
Fixes #789 
This changes the pipelines that have a federated server so that the federated server runs server "latest" (currently 10.12.1) with the current release of user_ldap (it gets it from the marketplace with a "php occ market" command). That ensures that the federated server has a server+app pair that is known to work.
The "local" server runs core daily-master-qa and the current branch of the user_ldap app. That has the current new code (Symfony 5 in this case) in both server core and user_ldap.
So this verifies that a "new" Symfony 5 installation with user_ldap can do federated sharing with a "latest" Symfony 4 installation - good.
=> [tests-only] [full-ci] Adjust drone CI of federated server

lib/Group_LDAP.php
Related to https://github.com/owncloud/enterprise/issues/5634.
This aligns with https://github.com/owncloud/core/pull/40840 so the users are returned alphabetically by uid
=> Use alphabetical order instead of natural order

.drone.star
- It is no longer possible to post a GitHub comment when an acceptance test pipeline fails. The token is no longer available to PRs. So remove this from CI.
- The earlyFail setting is not used any more in the code, so remove it.
Part of issue https://github.com/owncloud/QA/issues/820
=> [tests-only] Remove githubComment and unused earlyFail from drone CI

.drone.star
Fixes #803 
Remove select-encryption-type from the drone CI pipelines that run with core latest plus encryption and user_ldap.
core latest is now 10.13.0, and in 10.13.0 the select-encryption-type command was removed. Encryption now always defaults to masterkey.
=> [full-ci] [tests-only] Remove select-encryption-type occ command from CI

tests/acceptance/features/apiUserLDAP/sharingLocalUserLdapUser.feature
In this PR, the status code is updated from `500` to `404`, for `local-user` trying to download the file content shared by LDAP user.
Fixes: https://github.com/owncloud/user_ldap/issues/809
=> [tests-only][full-ci] update status code from 500 to 404

CHANGELOG.md, appinfo/info.xml, sonar-project.properties
The merge was forgotten, when the release was done.
Everything else (except version number bump and Changelog) found in the release branch is already in master. No need to do a full merge back.
=> Merge 0.18.0 version bump and CHANGELOG back to master

appinfo/app.php, js/wizard/wizardTabAdvanced.js, lib/AppInfo/Application.php, lib/Configuration.php, lib/Connection.php, lib/User/Manager.php, lib/User/UserEntry.php, lib/User_LDAP.php, lib/User_Proxy.php, templates/settings.php, tests/unit/User/ManagerTest.php, tests/unit/User/UserEntryTest.php, tests/unit/User_LDAPTest.php
Expose user attributes from LDAP to other apps.
The admin will expose some attributes for other apps to consume. For example, the admin could expose the `businessCategory`, `employeeType` and `employeeNumber` (assuming those attributes are available) so other apps can use that information.
By default, no attribute will be exposed. This means that other apps will have to use the information provided by core (check the core's `IUser` interface). The admin can add any attribute (one per line) in the user_ldap's wizard -> advanced tab -> special attributes -> exposed user attributes (at the bottom of the advanced tab).
Note that the information will be available for any app, so choose wisely what information you want to expose.
Other apps can access to those attributes via the …
=> Exposed attributes

.drone.star
This PR change the rocketchat notification server `chat` to `talk`.
Part of https://github.com/owncloud/QA/issues/846
=> [full-ci] [tests-only] Changed rocketchat notifications server

CHANGELOG.md, lib/AppInfo/Application.php, lib/User/Manager.php, lib/User_LDAP.php, tests/unit/User_LDAPTest.php
If there are no exposed attributes configured in the ldap's wizard, we shouldn't hit the LDAP server trying to get the exposed attributes.
Link: https://github.com/owncloud/enterprise/issues/6856
=> fix: do no hit LDAP if no exposed attribute is configured
